### ISSUE TITLE
Project review

### ISSUE THREAD

**Issue by mianzg** [ds4owd-001/project-bentono#6]
@Bentono Congrats again on accomplishing your capstone project! We are happy that you went through the course with us and applied the skills in the project.

I am reviewing your project on "Renewable Water Resources in Eastern Africa". Note that my review does not have any assessment on the writing content of the report, but I did enjoy reading it and learnt new stuff.

Please find the detailed feedback in the next section.

**Comment by mianzg** [comment]
@Bentono You completed most items in the [Required Items](https://ds4owd-001.github.io/website/project/#required-items). Awesome!
Some items that can be improved are:

**Technical**
1. Provide a label and a caption in the code chunk option for each figure and table. Notice that the label has to start with prefix `fig-` for figures and `tbl-` for tables
```
#| label: fig-yourfiglabel
#| fig-cap: "Renewable water resources in East Africa (2013-2017)"
```
2. Provide cross-reference to the figures and tables once you have done 1. For instance, change "Tabel 2" in line 261 to be `@tbl-yourtabellable`
3. Figure 2-4 are very beautifully plotted and visually appealing. However, I would **caution** that the figures might not be as informative as it looks like. The y-axis, color and bubble size all refer to the same variable which does not add more insights to interpret the plot. We could add one component to emphasise the variable, but use colour/size to show a third variable is more common (e.g. population <- I don't know if this is interesting for this analysis, then we can see if small population country has a small withdrawal). Furthermore, the figure does not have legend title so I had to look into the code to see what you mean with the color and bubble size, and this shouldn't be the case for figures. A figure should stand alone with its title, axis, caption, legends with sufficient text caption.

**Data**
Nice job with importing and cleaning the raw data. You also have well-documented dictionary csvfile and README. The processed data is exported too.

**Intellectual**
Concise report with all components needed in the instructions! The references are also automatically added. Clear introduction and method. I would like to have a bit more on interpreting findings from the figures as the current report uses more external information instead of describing the plots.

**Comment by Bentono** [comment]
@mianzg Thank you for the detailed review and kind feedback. I am happy to learn that I met most of the requirements.

I will attend to the comments and finalize the document by the 26th of April. 

Thank you.
